version: "3.8" # Versión del formato de docker-compose

services:
  localstack:
    container_name: localstack-todo-app
    image: localstack/localstack:latest

    ports:
      - "4566:4566"

    environment:
      - SERVICES=dynamodb,cognito-idp,lambda,apigateway,iam,sts,logs
      # dynamodb: Base de datos NoSQL
      # cognito-idp: Identity Provider (autenticación usuarios)
      # lambda: Funciones serverless
      # apigateway: API REST
      # iam: Roles y permisos
      # sts: Security Token Service (para asumir roles)
      # logs: CloudWatch Logs (logs de Lambdas)

      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse

      - LAMBDA_REMOTE_DOCKER=0

      - DOCKER_HOST=unix:///var/run/docker.sock
      # Socket de Docker (para que LocalStack pueda crear contenedores Lambda)

      - PERSISTENCE=1
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack

      - EDGE_PORT=4566

      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

    volumes:
      - ./localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
